### PR TITLE
v0.3 - Code Refactoring

### PR DESCRIPTION
**Pull request by fax1ty**
Updated everything that could be updated and deleted what could be deleted

### CODE REVIEW

**Comment by ankon** [comment]
Thank you.

Could you maybe describe a bit more what the changes are in detail, and why they were needed? The PR as is is quite a lot to review.

**Comment by fax1ty** [comment]
@ankon 
1) This commit closes https://github.com/Collaborne/cordova-gallery-api/issues/3 issue
Due to the lack of versioning, an error was mixed into the JSON. Because of what the JS part could not read JSON Object
2) I have simplified the Android `dev` folder structure
Removed all unnecessary to make it easier for developers to open it in Android Studio right away

**Comment by fax1ty** [comment]
@ankon 
`.iml` file is auto-generated. 
`cordova.jar` does not exist in the repository at all, you need to download/build it yourself, so as not to violate copyright. once the user adds this file to the "libs" folder and clicks "sync Gradle project" in .iml everything will be automatically changed. This file should be added to `.gitignore`

**Comment by ankon** [comment]
> .iml file is auto-generated.

That's fair, but then we can also drop it completely, couldn't we?

**Comment by fax1ty** [comment]
@ankon 
> 
> 
> Typo "ibs"?

check second commit. this line should not be at all



> 
> 
> > .iml file is auto-generated.
> 
> That's fair, but then we can also drop it completely, couldn't we?

as i also said ```This file should be added to .gitignore```

**Comment by fax1ty** [comment]
> 
> 
> The minimum API level needed for Google Play seems to be 28 (https://developer.android.com/distribute/best-practices/develop/target-sdk), so I think it would be good to also keep this in this library -- unless there's reasons to require something higher, of course.

??? targetSdkVersion = 29 

https://github.com/fax1ty/cordova-gallery-api/blob/d9286792ec14478ce7c7eb63a48b103b1284b630/dev/android/app/build.gradle#L9

**Comment by fax1ty** [comment]
I updated all dependencies and properties to be up-to-date

**Comment by fax1ty** [comment]
@ankon 
The new version of Cordova changed the import packages
I'll leave the assembled version of cordova-8.1.0 here
[cordova-8.1.0.jar.zip](https://github.com/Collaborne/cordova-gallery-api/files/3936536/cordova-8.1.0.jar.zip)

Also check last commit

**Pull request closed without merging**
